{{- if and .Values.controllerManager.webhook.enabled (eq .Values.global.certManagementMode "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kthena-controller-manager-webhook-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kthena-controller-manager-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - kthena-controller-manager-webhook.{{ .Release.Namespace }}.svc
    - kthena-controller-manager-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kthena-controller-manager-webhook-issuer
  secretName: {{ .Values.controllerManager.webhook.tls.certSecretName }}
{{- end }}
